---
version: '3.8'

services:
  mongodb:
    image: mongo:5.0.9
    container_name: mongodb-video
    environment:
      - MONGO_INITDB_ROOT_USERNAME=main_user
      - MONGO_INITDB_ROOT_PASSWORD=123123123
      - MONGO_INITDB_DATABASE=Stream
    volumes:
      - mongodb:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  mongodb: